IGogglesCare/IGogglesCare/Controllers/ProductController.cs
using IGogglesCare.Common;
using IGogglesCare.Database.DTO;
using IGogglesCare.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IGogglesCare.Controllers
{
    public class ProductController : Controller
    {
    
        // GET: Product
        public ActionResult Index()
        {
            ProductRepository productRepository = new ProductRepository();
            ViewBag.List = productRepository.GetProduct();
            return View();
        }


        public ActionResult Details(string Id)
        {
            ProductRepository productRepository = new ProductRepository();

            if (!String.IsNullOrEmpty(Id))
            {
                var item = productRepository.GetProduct(Convert.ToInt64(Id));
                ViewBag.item = item;
            }
           
            return View();
        }

        //Get Product
        public ActionResult CreateOrEdit(string Id)
        {
            if (!String.IsNullOrEmpty(Id))
            {
                long ItemId = 0;
                var IsId = Int64.TryParse(Id, out ItemId);
                if (IsId)
                {
                    ProductRepository productRepository = new ProductRepository();
                    var item = productRepository.GetProduct(ItemId);
                    ViewBag.Item = item;
                }
                else
                {
                    return View("All");
                }
            }
            else
            {

                ViewBag.Item = new DTOProduct();
            }
            return View();
        }
        [HttpPost]
        public ActionResult SaveProduct(DTOProduct obj, HttpPostedFileBase file)
        {
            RequestMessage requestMessage = new RequestMessage();

            // Initialize Respository
            ProductRepository objProductRepository = new ProductRepository();
            try
            {
                requestMessage.IsSuccess = true;

                //if (file != null)
                //{
                //    // Save Object Product
                //    string Image1Name = System.IO.Path.GetFileName(file.FileName);
                //    string Image2Name = System.IO.Path.GetFileName(file.FileName);
                //    string physicalPath = Server.MapPath("~/Content/ProductImages/" + Image1Name);
                //    file.SaveAs(physicalPath);

                //    obj.Image1 = Image1Name;
                




                    obj = objProductRepository.SaveProduct(obj);
               
                requestMessage.ResponseObject = obj;
            }
            catch (Exception ex)
            {
                requestMessage.IsSuccess = false;
                requestMessage.ResponseString = "Error in Saving Data";
                requestMessage.ResponseObject = ex;
            }


            // return to action
            return Json(requestMessage);
           
        }


    }
}

IGogglesCare/IGogglesCare/Controllers/SharedController.cs
using IGogglesCare.Database.DTO;
using IGogglesCare.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IGogglesCare.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public ActionResult Index()
        {
            return View();
        }

        ImageRepository imageRepository = new ImageRepository();

        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/Content/ProductImages/"), fileName);

                file.SaveAs(path);

                var dbImage = new DTOImages();
                dbImage.URL = fileName;

                long ImageId = imageRepository.SaveImage(dbImage);



                result.Data = new { Success = true, ImageURL = string.Format("~/Content/ProductImages/{0}", fileName) };

             
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

IGogglesCare/IGogglesCare/Views/Product/CreateOrEdit.cshtml
@{
    ViewBag.Title = "CreateOrEdit";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
    var item = ViewBag.item;

}


<div class="card">
    <div class="card-header">
        <h4>Create Product</h4>
    </div>

    <form action="/Product/SaveProduct" method="post">
        <input type="hidden" id="ProductId" name="ProductId">
        <div class="card-body">
            <div class="form-row">

                <div class="form-group col-md-6">
                    <label for="ProductName">Product Name</label>
                    <input type="text" class="form-control" id="Name" name="Name" value="@item.Name" placeholder="Product Name">
                </div>


                <div class="form-group col-md-6">
                    <label for="SKU">SKU</label>
                    <input type="text" class="form-control" id="SKU" name="SKU" value="@item.SKU" placeholder="SKU">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="Price">Price</label>
                    <input type="number" class="form-control" id="Price" name="Price" step="0.00000001" value="@item.Price" placeholder="Price">
                </div>

                <div class="form-group col-md-6">
                    <label for="EyeHeight">Eye Height</label>
                    <input type="number" class="form-control" id="EyeHeight" value="@item.EyeHeight" step="0.00000001" name="EyeHeight" placeholder="Eye Height">
                </div>

            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="EyeWidth col-md-6">Eye Width</label>
                    <input type="text" class="form-control" id="EyeWidth" step="0.00000001" value="@item.EyeWidth" name="EyeWidth"
                           placeholder="Eye Width">
                </div>

                <div class="form-group col-md-6">
                    <label for="NoseBridge ">Nose Bridge</label>
                    <input type="text" class="form-control" id="NoseBridge" step="0.00000001" value="@item.NoseBridge" name="NoseBridge"
                           placeholder="Nose Bridge">
                </div>

            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="TempleSize">Temple Size</label>
                    <input type="number" class="form-control" id="TempleSize" step="0.00000001" value="@item.TempleSize" name="TempleSize"
                           placeholder="Temple Size">
                </div>

                <div class="form-group col-md-6">
                    <label for="FrameSize">Frame Size</label>
                    <input type="number" class="form-control" id="FrameSize" step="0.00000001" value="@item.FrameSize" name="FrameSize"
                           placeholder="Frame Size">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="FrameShape">Frame Shape</label>
                    <input type="text" name="FrameShape" class="form-control" step="0.00000001" value="@item.FrameShape" id="FrameShape"
                           placeholder="Frame Shape">
                </div>

                <div class="form-group col-md-6">
                    <label for="ProductQuantity">Product Stock</label>
                    <input type="number" name="ProductQuantity" class="form-control" step="0.00000001" value="@item.ProductQuantity" id="ProductQuantity"
                           placeholder="Product Quantity">
                </div>
            </div>
            <div class="form-row">
                @*<div class="form-group col-md-6">
                        <label for="inputCity">City</label>
                        <input type="text" class="form-control" id="inputCity">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputState">State</label>
                        <select id="inputState" class="form-control">
                            <option selected>Choose...</option>
                            <option>...</option>
                        </select>
                    </div>*@
                <div class="form-group col-md-3">
                    <label for="Image1">Image 1</label>

                    <input type="hidden" id="Thumbnail" name="Thumbnail" />
                    <input class="form-control" id="imageUpload" name="Thumbnail" type="file" accept=".png, .jpg" />
                </div>


            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="Material">Material</label>
                    <input type="text" name="Material" class="form-control" value="@item.Material" id="Material"
                           placeholder="Material ">
                </div>
                <div class="form-group col-md-6">
                    <label for="">Feature on Main Page</label>


                    <select name="IsFeatured" class="form-control">

                        @if (item.IsFeatured == true)
                        {

                            <option id="IsFeatured" selected value="true">Yes</option>
                            <option id="IsFeatured" value="false">No</option>
                        }
                        else if (item.IsFeatured == false)
                        {
                            <option id="IsFeatured" value="true">Yes</option>
                            <option id="IsFeatured" selected value="false">No</option>
                        }
                        else
                        {
                            <option selected value="false" disabled>Select Options</option>

                            <option id="IsFeatured" value="true">Yes</option>
                            <option id="IsFeatured" value="false">No</option>

                        }




                    </select>
                </div>
            </div>




            <div class="form-group">
                <label for="Description">Description</label>
                <input type="text" class="form-control" id="Description" name="Description" value="@item.Description" placeholder="Description" required="">
                <div class="invalid-feedback">
                    Description is needed
                </div>
            </div>


            <div class="form-group">
                <div class="thumb">
                    <img class="img-thumbnail img-fluid" id="productImage" src="~/Content/ProductImages/glass.jpg" />
                </div>
                </div>

            </div>

        </div>




        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<script>
$("#imageUpload").change(function () {
		var element = this;

		var formData = new FormData();

		var totalFiles = element.files.length;

		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}

		$.ajax({
			type: 'POST',
			url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
            })
            .done(function (response) {
          
            console.log(response);

            if (response.Success) {
                $("#Thumbnail").val(response.ImageURL);
                $("#productImage").attr("src", response.ImageURL);
            }
            })
    .fail(function (XMLHttpRequest, textStatus, errorThrown) {
    alert("FAIL");
         });
    });
</script>

IGogglesCare/IGogglesCare/Views/Product/Index.cshtml
@{
    ViewBag.Title = "EyeGlasses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/style.css" rel="stylesheet" />
@*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">*@

<!--New Arrivals-->
<div class="product-rows section">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <div class="section-header text-center">
                    <h2 class="h2">New Arrivals</h2>
                    <p>Grab these new items before they are gone!</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div id="content" class="my-5">
        <div id="filterbar" class="collapse">
            <div class="box border-bottom">
                <div class="form-group text-center">
                    <div class="btn-group" data-toggle="buttons"> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="radio"> Reset </label> <label class="btn btn-success form-check-label active"> <input class="form-check-input" type="radio" checked> Apply </label> </div>
                </div>
                <div> <label class="tick">New <input type="checkbox" checked="checked"> <span class="check"></span> </label> </div>
                <div> <label class="tick">Sale <input type="checkbox"> <span class="check"></span> </label> </div>
            </div>
            @*<div class="box border-bottom">
                    <div class="box-label text-uppercase d-flex align-items-center">Outerwear <button class="btn ml-auto" type="button" data-toggle="collapse" data-target="#inner-box" aria-expanded="false" aria-controls="inner-box" id="out" onclick="outerFilter()"> <span class="fas fa-plus"></span> </button> </div>
                    <div id="inner-box" class="collapse mt-2 mr-1">
                        <div class="my-1"> <label class="tick">Windbreaker <input type="checkbox" checked="checked"> <span class="check"></span> </label> </div>
                        <div class="my-1"> <label class="tick">Jumpsuit <input type="checkbox"> <span class="check"></span> </label> </div>
                        <div class="my-1"> <label class="tick">Jacket <input type="checkbox"> <span class="check"></span> </label> </div>
                        <div class="my-1"> <label class="tick">Coat <input type="checkbox"> <span class="check"></span> </label> </div>
                        <div class="my-1"> <label class="tick">Raincoat <input type="checkbox"> <span class="check"></span> </label> </div>
                        <div class="my-1"> <label class="tick">Handbag <input type="checkbox" checked> <span class="check"></span> </label> </div>
                        <div class="my-1"> <label class="tick">Warm vest <input type="checkbox"> <span class="check"></span> </label> </div>
                        <div class="my-1"> <label class="tick">Wallets <input type="checkbox" checked> <span class="check"></span> </label> </div>
                    </div>
                </div>
                <div class="box border-bottom">
                    <div class="box-label text-uppercase d-flex align-items-center">season <button class="btn ml-auto" type="button" data-toggle="collapse" data-target="#inner-box2" aria-expanded="false" aria-controls="inner-box2"><span class="fas fa-plus"></span></button> </div>
                    <div id="inner-box2" class="collapse mt-2 mr-1">
                        <div class="my-1"> <label class="tick">Spring <input type="checkbox" checked="checked"> <span class="check"></span> </label> </div>
                        <div class="my-1"> <label class="tick">Summer <input type="checkbox"> <span class="check"></span> </label> </div>
                        <div class="my-1"> <label class="tick">Autumn <input type="checkbox" checked> <span class="check"></span> </label> </div>
                        <div class="my-1"> <label class="tick">Winter <input type="checkbox"> <span class="check"></span> </label> </div>
                        <div class="my-1"> <label class="tick">Rainy <input type="checkbox"> <span class="check"></span> </label> </div>
                    </div>
                </div>
                <div class="box border-bottom">
                    <div class="box-label text-uppercase d-flex align-items-center">price <button class="btn ml-auto" type="button" data-toggle="collapse" data-target="#price" aria-expanded="false" aria-controls="price"><span class="fas fa-plus"></span></button> </div>
                    <div class="collapse" id="price">
                        <div class="middle">
                            <div class="multi-range-slider">
                                <input type="range" id="input-left" min="0" max="100" value="10"> <input type="range" id="input-right" min="0" max="100" value="50">
                                <div class="slider">
                                    <div class="track"></div>
                                    <div class="range"></div>
                                    <div class="thumb left"></div>
                                    <div class="thumb right"></div>
                                </div>
                            </div>
                        </div>
                        <div class="d-flex align-items-center justify-content-between mt-2">
                            <div> <span id="amount-left" class="font-weight-bold"></span> uah </div>
                            <div> <span id="amount-right" class="font-weight-bold"></span> uah </div>
                        </div>
                    </div>
                </div>*@
            <div class="box">
                <div class="box-label text-uppercase d-flex align-items-center">size <button class="btn ml-auto" type="button" data-toggle="collapse" data-target="#size" aria-expanded="false" aria-controls="size"><span class="fas fa-plus"></span></button> </div>
                <div id="size" class="collapse">
                    <div class="btn-group d-flex align-items-center flex-wrap" data-toggle="buttons"> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox"> 80 </label> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox" checked> 92 </label> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox" checked> 102 </label> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox" checked> 104 </label> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox" checked> 106 </label> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox" checked> 108 </label> </div>
                </div>
            </div>
        </div>
        <div id="products">
            <div class="row mx-0">
                   
                @foreach (var item in ViewBag.List)
               

                {


                <div class="col-lg-4 col-md-6 pt-md-0 pt-3" onclick="window.location.href='/Product/Details/@item.ProductId'">
                    <div class="card d-flex flex-column align-items-center">
                        <div class="product-name">@item.Name</div>
                        <div class="card-img"> <img src="~/Content/ProductImages/@item.Thumbnail" alt="" height="10" id="shirt"> </div>
                        <div class="text-muted text-center mt-auto">Available Sizes</div>
                        <div id="avail-size">
                            <div class="btn-group d-flex align-items-center flex-wrap" data-toggle="buttons"> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox"> 80 </label> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox" checked> 92 </label> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox" checked> 102 </label> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox" checked> 104 </label> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox" checked> 106 </label> <label class="btn btn-success form-check-label"> <input class="form-check-input" type="checkbox" checked> 108 </label> </div>
                        </div>
                        <div class="card-body pt-0">
                            <div class="text-muted text-center mt-auto">Available Colors</div>
                            <div class="d-flex align-items-center justify-content-center colors my-2">
                                <div class="btn-group" data-toggle="buttons" data-tooltip="tooltip" data-placement="right" title="choose color"> <label class="btn btn-light border form-check-label"> <input class="form-check-input" type="radio" autocomplete="off"> </label> <label class="btn btn-blue form-check-label active"> <input class="form-check-input" type="radio" autocomplete="off"> </label> <label class="btn btn-green form-check-label"> <input class="form-check-input" type="radio" autocomplete="off"> </label> <label class="btn btn-orange form-check-label"> <input class="form-check-input" type="radio" autocomplete="off"> </label> <label class="btn btn-pink form-check-label"> <input class="form-check-input" type="radio" autocomplete="off"> </label> </div>
                            </div>
                            <div class="d-flex align-items-center price">
                                <div class="del mr-2"><span class="text-dark">5500 uah</span></div>
                                <div class="font-weight-bold">4500 uah</div>
                            </div>
                        </div>
                    </div>
                </div>

                }
            </div>
        </div>
    </div>
</div>
<!--End Featured Product-->
<!--Parallax Section-->
<div class="section">
    <div class="hero hero--large hero__overlay bg-size">
        <img class="bg-img" src="~/Content/assets/images/parallax-banners/eyeglasses_1900x990.jpg" alt="" />
    </div>
</div>
<!--End Parallax Section-->
<!--For Newsletter Popup-->
<script>
    jQuery(document).ready(function () {
        jQuery('.closepopup').on('click', function () {
            jQuery('#popup-container').fadeOut();
            jQuery('#modalOverly').fadeOut();
        });

        var visits = jQuery.cookie('visits') || 0;
        visits++;
        jQuery.cookie('visits', visits, { expires: 1, path: '/' });
        console.debug(jQuery.cookie('visits'));
        if (jQuery.cookie('visits') > 1) {
            jQuery('#modalOverly').hide();
            jQuery('#popup-container').hide();
        } else {
            var pageHeight = jQuery(document).height();
            jQuery('<div id="modalOverly"></div>').insertBefore('body');
            jQuery('#modalOverly').css("height", pageHeight);
            jQuery('#popup-container').show();
        }
        if (jQuery.cookie('noShowWelcome')) { jQuery('#popup-container').hide(); jQuery('#active-popup').hide(); }
    });

    jQuery(document).mouseup(function (e) {
        var container = jQuery('#popup-container');
        if (!container.is(e.target) && container.has(e.target).length === 0) {
            container.fadeOut();
            jQuery('#modalOverly').fadeIn(200);
            jQuery('#modalOverly').hide();
        }
    });

    /*--------------------------------------
        Promotion / Notification Cookie Bar
      -------------------------------------- */
    if (Cookies.get('promotion') != 'true') {
        $(".notification-bar").show();
    }
    $(".close-announcement").on('click', function () {
        $(".notification-bar").slideUp();
        Cookies.set('promotion', 'true', { expires: 1 });
        return false;
    });
</script>
<!--End For Newsletter Popup-->